### ISSUE TITLE
Live-Caption Tool Re-implementation

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#104]

**Comment by bhajneet** [comment]
- [ ] Live Caption Tool Additions #48 (make changes to live captions to the app itself so users don't have to fiddle with custom CSS, include one "blank" CSS in the dropdown so advanced users can set up multiple scenes or allow multiple 3rd party computers to connect for various programs)
- [ ] Fixed box size #47 (add option to fit gurbani/english or whatever visible fields are there in one line by appropriately resizing text, this is still too advanced for most users, but a few have requested it, so leave it off by default for sure or perhaps add a new "min font size" slider which doesn't allow it to go smaller than that even if it bleeds to two lines)
- [ ] add overlay css file selector #197 (drop down that is populated by css files in user directory)
- [ ] Add time & date overlays #200 (as an endpoint that can be manipulated by url, e.g. localhost:1699/timedaydate?format="HH:mm ddd DD M YY") must have the "esc" screen true/false in it as well
- [ ] add url address to overlay #201 (something that can be easily copy and pasted across the network)
- [ ] Live Captions Customization #353
