### ISSUE TITLE
To-Do Checklist

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#28]
- [x] Database:
  - [x] https://github.com/ShabadOS/database/issues/6 Track Diffs
  - [x] https://github.com/ShabadOS/database/issues/7 Reduce file size 
  - [x] #10 Decouple from updates
  - [x] https://github.com/ShabadOS/database/issues/8 Add Unicode column
- [ ] #29 Backend -> Node.js
  - [ ] #30 Add Usage Analytics (Matomo)
  - [x] #31 Sentry for error reporting/crashes
  - [ ] #41 Backend CLI
- [x] #26 Frontend -> React
- [ ] #32 Create tutorial
- [ ] Settings:
  - [x] #11 Decouple from updates
  - [x] #33 Fix defaults
  - [ ] #16 Add option for margin.
  - [ ] #21 Add custom background images
  - [ ] #34 Add animated backgrounds
- [x] #12 Live Captions Tool
- [ ] #35 Chromecast App
- [ ] #36 Mobile App (iOS and Android)
- [ ] #37 macOS Release (optional: App Store) 
- [ ] https://github.com/ShabadOS/database/issues/19 Fuzzy Search 
- [ ] #38 Presentation Clicker/Remote integration
- [ ] #39 Documentation
- [ ] Create short videos/picture-guides for tutorials, set up, explanations
- [ ] Confirm Firewall settings on startup or include notice during installer to allow access
- [x] Linux Snap support (optional: Flatpak support)
- [ ] Windows 10 store
- [x] API for converting ASCII to Unicode

**Comment by Harjot1Singh** [comment]
@bhajneet do you want to clean this up?

**Comment by bhajneet** [comment]
Yes, I want to close this issue as it doesn't get much visibility in our issues list

I think a PR or projects is better suited for this. Or maybe we can add this issue to the readme so it has more visibility?

**Comment by Harjot1Singh** [comment]
Projects is best suited to this.

**Comment by Harjot1Singh** [comment]
@bhajneet

**Comment by bhajneet** [comment]
Moved to [milestones](https://github.com/ShabadOS/desktop/milestones?direction=asc&sort=due_date&state=open)
